---
# tasks file for ntp
- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ ntp_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(ntp_packages[ansible_distribution]
      | default(ntp_packages['default'] )) }}"

- name: configure ntp_interfaces
  lineinfile:
    path: "{{ ntp_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(ntp_configuration[ansible_distribution]
      | default(ntp_configuration['default'] )) }}"
    line: "interface listen {{ item.address }}"
  with_items:
    - "{{ ntp_interfaces }}"
  when:
    - ntp_interfaces is defined

- name: configure ntp_restrict
  lineinfile:
    path: "{{ ntp_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(ntp_configuration[ansible_distribution]
      | default(ntp_configuration['default'] )) }}"
    line: "restrict {{ item.address }}"
  with_items:
    - "{{ ntp_restrict }}"
  when:
    - ntp_restrict is defined

- name: configure ntp_pool
  lineinfile:
    path: "{{ ntp_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(ntp_configuration[ansible_distribution]
      | default(ntp_configuration['default'] )) }}"
    line: "pool {{ item.name }}"
  with_items:
    - "{{ ntp_pool }}"
  when:
    - ntp_pool is defined

- name: configure ntp_server
  lineinfile:
    path: "{{ ntp_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(ntp_configuration[ansible_distribution]
      | default(ntp_configuration['default'] )) }}"
    line: "server {{ item.name }}"
  with_items:
    - "{{ ntp_server }}"
  when:
    - ntp_server is defined

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - "{{ ntp_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(ntp_services[ansible_distribution]
      | default(ntp_services['default'] )) }}"
