---
# tasks file for ntp
- name: lookup and rename variables
  set_fact:
    file: "{{ item.file }}"
    packages: "{{ item.packages }}"
    service: "{{ item.service }}"
  with_items:
    - "{{ ntp_configuration[ansible_distribution]
      | default(ntp_configuration['default'] ) }}"

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ packages }}"

- name: configure ntp_interfaces
  lineinfile:
    dest: "{{ file }}"
    line: "interface listen {{ item.address }}"
  with_items:
    - "{{ ntp_interfaces }}"
  when:
    - ntp_interfaces is defined
  notify:
    - restart ntpd

- name: configure ntp_restrict
  lineinfile:
    dest: "{{ file }}"
    line: "restrict {{ item.address }}"
  with_items:
    - "{{ ntp_restrict }}"
  when:
    - ntp_restrict is defined
  notify:
    - restart ntpd

- name: configure ntp_pool
  lineinfile:
    dest: "{{ file }}"
    line: "pool {{ item.name }}"
  with_items:
    - "{{ ntp_pool }}"
  when:
    - ntp_pool is defined
  notify:
    - restart ntpd

- name: configure ntp_server
  lineinfile:
    dest: "{{ file }}"
    line: "server {{ item.name }}"
  with_items:
    - "{{ ntp_server }}"
  when:
    - ntp_server is defined
  notify:
    - restart ntpd

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - "{{ service }}"
