---
# handlers file for ntp
- name: restart ntp
  service:
    name: "{{ ntp_service[ansible_distribution]
          | default(ntp_service['default']) }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
